image: atlassian/default-image:3

pipelines:
  branches:
    develop:
      - step:
          script:
            - pipe: atlassian/ssh-run:0.4.1
              variables:
                SSH_USER: $HOST_USER
                SERVER: $HOST
                PORT: $SSH_PORT
                MODE: 'script'
                COMMAND: 'dev-deploy-script.sh'