class Types::Enums::ControlColumns < Types::BaseEnum
  value "id", "id"
  value "type_of_control", "type_of_control"
  value "nature", "nature"
  value "assertion", "assertion"
  value "ipo", "ipo"
  value "control_owner", "control_owner"
  value "created_at", "created_at"
  value "updated_at", "updated_at"
  value "status", "status"
  value "key_control", "key_control"
  value "description", "description"
  value "draft_id", "draft_id"
  value "published_at", "published_at"
  value "trashed_at", "trashed_at"
  value "user_reviewer_id", "user_reviewer_id"
  value "created_by", "created_by"
  value "last_updated_by", "last_updated_by"
end