class Types::Enums::PolicyColumns < Types::BaseEnum
  value "title","title"
  value "description","description"
  value "policy_category_id","policy_category_id"
  value "created_at", "created_at"
  value "updated_at","updated_at"
  value "user_id", "user_id"
  value "ancestry", "ancestry"
  value "status","status"
  value "visit","visit"
  value "resource_id", "resource_id"
  value "draft_id", "draft_id"
  value "published_at","published_at"
  value "trashed_at","trashed_at"
  value "user_reviewer_id","user_reviewer_id"
  value "recent_visit","recent_visit"
  value "is_submitted","is_submitted"
  value "created_by","created_by"
  value "last_updated_by","last_updated_by"
  value "last_updated_at","last_updated_at"
  value "true_version", "true_version"
end