class Types::Enums::RiskColumns < Types::BaseEnum
  value "name","name"
  value "created_at","created_at"
  value "updated_at","updated_at"
  value "level_of_risk","level_of_risk"
  value "status","status"
  value "type_of_risk","type_of_risk"
  value "draft_id","draft_id"
  value "published_at","published_at"
  value "trashed_at","trashed_at"
  value "user_reviewer_id","user_reviewer_id"
  value "created_by","created_by"
  value "last_updated_by","last_updated_by"
  value "business_process","business_process"
end